### ISSUE TITLE
bcftools norm issue

### ISSUE THREAD

**Issue by xiaomaozhu** [samtools/bcftools#601]
Original variant:
chr1    3642316 .       T       TGGATGGAT
bcftools norm left-align above variant to:
chr1    3642315 .       A       ATGGATGGA
However, using algorism from publication https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4481842/, it's left-aligned to:
chr1    3642311 .       G       GTGGATGGA 
Why bcftools does not left-shift to 3642311?

**Comment by pd3** [comment]
Can you show also the context and the reference sequence?

      samtools faidx ref.fa chr1:3642311-3642317
      bcftools query -f'%CHROM:%POS  %REF %ALT\n' file.bcf -r chr1:3642311-3642317

**Comment by bogdanionescu2** [comment]
Here are the outputs you asked for:

FASTA lookup (HG19) results:
>chr1:3642311-3642324
gtggatggatggat

Variants context for the bcftool run:
chr1    3585079 CGTGTGTGTGT     CGTGTGTGTGTGTGTGT
chr1    3596371 CTCTCTG C
chr1    3613710 GCGGGGCCCACCTCGCACCCGCGGCCCACGTCGCACC   G
chr1    3640134 TCTGC   T
chr1    3640687 T       TA
**chr1    3642316 T       TGGATGGAT**
chr1    3642669 GTGGA   G

**Comment by pd3** [comment]
I just tested your example and it was aligned to 

     1	3642311	ori_3642316	G	GTGGATGGA	.	.	.

Is it possible that you are using some old version of bcftools?

**Comment by bogdanionescu2** [comment]
Thank you for your quick response.

We have downloaded the latest version of bcf tools from here http://www.htslib.org/download/ and run the following command:

bcftools norm -f hg19.fasta 11_variants.vcf -c x -O v -o 11_variants_aligned.vcf

Attached you have the input and output files with 3642316 variant aligned to 3642315.

Could please left align the attached input file (11_variants.vcf) and let us know what is your command line?

Thank you.


[input and output vcf.zip](https://github.com/samtools/bcftools/files/973128/input.and.output.vcf.zip)

**Comment by pd3** [comment]
Hmm, it works for me. First I changed the ID column to show the original coordinate, the output from bcftools version 1.4 looks like this:

            bcftools-1.4 norm -f hs37d5.fa 11_variants.vcf -c x | grep -v ^# | grep 3642316
            Lines   total/split/realigned/skipped:	11/0/2/0
            1	3642311	ori_3642316	G	GTGGATGGA	209	....

Maybe the difference is in the reference genome? Try

           samtools faidx hs37d5.fa 1:3585079-3645556 | tail -n +2 | md5sum
           1ea67e39a4f56cb737b21910de32959c  -

**Comment by bogdanionescu2** [comment]
You were right. Our fasta file had lower case nucleotides in it and bcftools is not case insensitive.
Thank you for your assistance in this matter!

**Comment by pd3** [comment]
This is now fixed, norm is now case-insensitive. Thanks for the bug report!

**Comment by stevekm** [comment]
in which version was this change applied? I am using:
```
bcftools 1.3
Using htslib 1.3
```

and my reference fasta appears to have lower case letters at a region which is causing a similar problem.

**Comment by stevekm** [comment]
Here is the variant that is causing this issue for me:
```
chrX	66766356	.	TGGCGGCGGCGGC	T	413.73	.	AC=2;AF=1.00;AN=2;DP=49;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=60.64;QD=31.83;SOR=1.609	GT:AD:DP:GQ:PL	1/1:0,13:13:43:451,43,0
```

Here is the command I am using: 

```
$ bcftools norm --multiallelics -both NC-HAPMAP.original.vcf | bcftools norm --fasta-ref ref/iGenomes/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa - | grep '6676635'
```

output:

```
Lines   total/split/realigned/skipped:	1470/9/0/0
Lines   total/split/realigned/skipped:	1479/0/7/0

chrX	66766356	.	TGGCGGCGGCGGC	T	413.73	.	AC=2;AF=1;AN=2;DP=49;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;MQ=60.64;QD=31.83;SOR=1.609GT:AD:DP:GQ:PL	1/1:0,13:13:43:451,43,0

```
the region from my reference file:

```
$ samtools faidx ref/iGenomes/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa chrX:66766340-66766370
>chrX:66766340-66766370
gtggtggtgggggtggtggcggcggcggcgg
```

cant get `bcftools query` to work, it keeps saying 'unable to load index' for my bgzip'd and indexed vcf

**Comment by mcshane** [comment]
The fix went into 1.5. Current version is 1.8

**Comment by stevekm** [comment]
Thanks. I upgraded to version 1.7, and the issue still remains. Any idea why this variant is not normalizing correctly?

**Comment by pd3** [comment]
Sorry, I don't understand what the problem is. The output looks correct, while your suggested output is not a valid VCF record.

The second issue with indexing, is probably due to fact that your VCF is not properly indexed?
